language: node_js

node_js:
  - "5.10.1"
  - "5"
  - "4.4.3"
  - "4"
  - "0.12"
  - "0.10"
  - "node"
  
before_script:
    - npm install

script:
    - npm run-script lint -loglevel silent
    - npm run-script test -loglevel silent
    
after_success:
    - export BUILD_RESULT="SUCCESS"

after_failure:
    - export BUILD_RESULT="ERRORED"
    
