language: node_js

node_js:
  - "node"
  - "5"
  - "4.4.3"
  - "4"
  - "0.12"
  - "0.10"
  
before_script:
    - npm install

script:
    - ./node_modules/.bin/jshint --verbose server/**/*.js client/interface/app/**/*.js server.js
    - ./node_modules/.bin/htmlhint --config .htmlhintrc client/**/*.html
    - npm run-script test
    
after_success:
    - export BUILD_RESULT="SUCCESS"

after_failure:
    - export BUILD_RESULT="ERRORED"
    
